### ISSUE TITLE
Type 'Web3AuthConnector' is not assignable to type 'Connector<any, any, any>'.

### ISSUE THREAD

**Issue by aalmada** [Web3Auth/web3auth-wagmi-connector#12]
I have in my `packages.json` the following:

```
"@web3auth/web3auth-wagmi-connector": "^1.0.0",
"wagmi": "^0.7.7",
```

I added the `Web3AuthConnector` as shown in the READ.ME but I'm getting the following compilation error:

```
TS2322: Type 'Web3AuthConnector' is not assignable to type 'Connector<any, any, any>'.
  Types of property 'chains' are incompatible.
    Type 'import("/Users/antao.almada/Projects/test/node_modules/@web3auth/web3auth-wagmi-connector/node_modules/@wagmi/core/dist/declarations/src/types/index").Chain[]' is not assignable to type 'import("/Users/antao.almada/Projects/test/packages/launchwebsite/node_modules/@wagmi/core/dist/declarations/src/types/index").Chain[]'.
      Type 'import("/Users/antao.almada/Projects/test/node_modules/@web3auth/web3auth-wagmi-connector/node_modules/@wagmi/core/dist/declarations/src/types/index").Chain' is not assignable to type 'import("/Users/antao.almada/Projects/test/packages/launchwebsite/node_modules/@wagmi/core/dist/declarations/src/types/index").Chain'.
        Types of property 'ens' are incompatible.
          Type '{ address: string; } | undefined' is not assignable to type '{ address: `0x${string}`; } | undefined'.
            Type '{ address: string; }' is not assignable to type '{ address: `0x${string}`; }'.
              Types of property 'address' are incompatible.
                Type 'string' is not assignable to type '`0x${string}`'.
    35 |                        },
    36 |                }),
  > 37 |                new Web3AuthConnector({
       |                ^^^^^^^^^^^^^^^^^^^^^^^
  > 38 |                        chains,
       | ^^^^^^^^^^
  > 39 |                        options: {
       | ^^^^^^^^^^
  > 40 |                                enableLogging: true,
       | ^^^^^^^^^^
  > 41 |                                clientId:
       | ^^^^^^^^^^
  > 42 |                                        'OUR_CLIENT_ID', // Get your own client id from https://dashboard.web3auth.io
       | ^^^^^^^^^^
  > 43 |                                network: 'testnet', // web3auth network
       | ^^^^^^^^^^
  > 44 |                                chainId: '0x1', // chainId that you want to connect with
       | ^^^^^^^^^^
  > 45 |                        },
       | ^^^^^^^^^^
 > 46 |                }),
       | ^^^^^
    47 |        ],
    48 |        provider,
    49 |        webSocketProvider,

```

I see that you only support `"@wagmi/core": "^0.5.7"` Do you plan to support a newer version any time soon?

**Comment by grmkris** [comment]
I can still use wagmi and ignore this error and things work on first glance... but first issue that I encountered is that 

useNetwork hook returns no data

would be great if we can get this sorted

**Comment by jjjjjjjjjjjjjjjjacob** [comment]
This breaks the connector. Currently iterating through all versions of Wagmi since 2 versions ago until I find one that doesn't break... Either the connector needs to be updated or someone needs to denote which range of versions it is compatible with.

UPDATE: I was able to get it to not entirely break by switching wagmi to v0.6.3 (the same in the example), and by adding the `socialLoginConfig: {mfaLevel: 'default'}` to the Web3AuthConnector constructor... but now there's no `Connect Wallet` option on the Web3Modal.

**Comment by myssynglynx** [comment]
v0.6.6 seems to be stable. add `"wagmi": "0.6.6",` to your package.json and you should be fine. Looking forward to being able to use the latest wagmi's with this :)

**Comment by yashovardhan** [comment]
Can you all test the latest version? `socialLoginConfig` should not be required

**Comment by ryanberckmans** [comment]
@chaitanyapotti this error still occurs with wagmi v0.11.2 and @web3auth/web3auth-wagmi-connector v2.1.1.

@wagmi/core latest is v0.9.x and web3auth-wagmi-connector is built against v0.8.x.

**Comment by chaitanyapotti** [comment]
That's because we follow the release pattern of rainbowkit which is still dependent on wagmi/core@0.8.x
Once they update, we will update this library

**Comment by ryanberckmans** [comment]
Ok, thanks.

**Comment by ander-db** [comment]
Hey everyone! I've encouter the same issue. RainbowKit it's already using wagmi 0.9.0. Any predition of when this library is going to be updated??

**Comment by yashovardhan** [comment]
We will be updating it as soon as possible.

**Comment by ander-db** [comment]
That's great!!

Thanks for the fast response!

**Comment by benjileibo** [comment]
@yashovardhan do you have a PR we can follow? Do you have a time estimate here and are there any workarounds?

**Comment by yashovardhan** [comment]
In the meantime, you can use wagmi library on the previous version.

**Comment by benjileibo** [comment]
> In the meantime, you can use wagmi library on the previous version.

Thanks for the quick reply @yashovardhan. Still getting the following error rolling back to wagmi 0.5.7

`Error: require() of ES Module /Users/benleibowitz/Github/PatientPortal/node_modules/@web3auth/web3auth-wagmi-connector/node_modules/@wagmi/core/dist/index.js from /Users/benleibowitz/Github/PatientPortal/node_modules/@web3auth/web3auth-wagmi-connector/dist/web3authWagmiConnector.cjs.js not supported.
Instead change the require of index.js in /Users/benleibowitz/Github/PatientPortal/node_modules/@web3auth/web3auth-wagmi-connector/dist/web3authWagmiConnector.cjs.js to a dynamic import() which is available in all CommonJS modules.`

**Comment by benjileibo** [comment]
Any sense of what's happening here @yashovardhan? Sorry to bug you - this is pressing on our side

**Comment by yashovardhan** [comment]
@benjileibo can you check the wagmi version in our sample apps and use that version.

https://github.com/Web3Auth/examples/tree/main/wagmi-connector

**Comment by LyghtCode** [comment]
> > In the meantime, you can use wagmi library on the previous version.
> 
> Thanks for the quick reply @yashovardhan. Still getting the following error rolling back to wagmi 0.5.7
> 
> `Error: require() of ES Module /Users/benleibowitz/Github/PatientPortal/node_modules/@web3auth/web3auth-wagmi-connector/node_modules/@wagmi/core/dist/index.js from /Users/benleibowitz/Github/PatientPortal/node_modules/@web3auth/web3auth-wagmi-connector/dist/web3authWagmiConnector.cjs.js not supported. Instead change the require of index.js in /Users/benleibowitz/Github/PatientPortal/node_modules/@web3auth/web3auth-wagmi-connector/dist/web3authWagmiConnector.cjs.js to a dynamic import() which is available in all CommonJS modules.`

Also getting this error and I am following the example repo you linked^ same versions.

**Comment by chaitanyapotti** [comment]
Please update to 3.0.0 and report if you face any issues

**Comment by ander-db** [comment]
> Please update to 3.0.0 and report if you face any issues

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'project/node_modules/ethers/lib/utils' imported from project/node_modules/@web3auth/web3auth-wagmi-connector/dist/web3authWagmiConnector.esm.js
Did you mean to import ethers/lib/utils.js?
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/'
}
```

**Comment by ryanberckmans** [comment]
@chaitanyapotti this issue has been resolved for me with 3.0.0 and wagmi 0.11.x and 0.12.x.

**Comment by yashovardhan** [comment]
Awesome @ryanberckmans thanks for letting us know. Closing this issue.

**Comment by ryanberckmans** [comment]
@yashovardhan great thanks. I am going to hijack your attention here and request that you investigate this issue https://github.com/Web3Auth/web3auth-wagmi-connector/issues/45 as it is preventing me from signing ordinary erc20 transfers in dev with chainId param set.
