### ISSUE TITLE
The example in the READ.ME is missing the mandatory socialLoginConfig property

### ISSUE THREAD

**Issue by aalmada** [Web3Auth/web3auth-wagmi-connector#13]

**Comment by wesleyfsmith** [comment]
I had the same issue.

**Comment by yashovardhan** [comment]
Can you please elaborate the issue? I don't see the socialLoginConfig properly being mandatory in this connector.

**Comment by aalmada** [comment]
I'm no longer trying to use this connector so I can't elaborate. What I remember is that, it didn't work when the `socialLoginConfig` property was missing.

**Comment by chaitanyapotti** [comment]
This is no longer relevant with the new version
