### ISSUE TITLE
Make connector option to Enable External Wallets in the Modal

### ISSUE THREAD

**Issue by angrooster** [Web3Auth/web3auth-wagmi-connector#16]
Currently there is no External Wallets option on the modal provided

Please add an option to enable it in the modal

Currently I have to implement the Wallet Connect buttons myself in a separate modal

Which breaks a cohesive User Experience

**Comment by jjjjjjjjjjjjjjjjacob** [comment]
+1. No wallet connection option defeats the purpose of this connector.

**Comment by yashovardhan** [comment]
When we are using the wagmi connector and rainbow kit, I don't particularly see the need to external wallet adapters, you can directly use the rainbow kit and wagmi connector external wallets right?

Web3Auth's main function here remains to get you connected with socials
