### ISSUE TITLE
SyntaxError: Illegal return statement

### ISSUE THREAD

**Issue by chenstanilovsky** [Web3Auth/web3auth-wagmi-connector#32]
Hi

The following code is throwing a syntax error on the server side when using it within a client component of Nextjs 13

```
 `const { connectAsync } = useConnect({
        connector: new Web3AuthConnector({
            chains,
            options: {
                enableLogging: true,
                clientId: process.env.WEB3AUTH_CLIENT_ID,
                network: 'testnet',
                chainId: '0x1'
            }
        })
    });`
```

SyntaxError: Illegal return statement
    at (sc_client)/./node_modules/@toruslabs/eccrypto/index.js

Any idea how I can resolve this?

    "@web3auth/modal": "^3.2.0",
    "@web3auth/web3auth-wagmi-connector": "^1.0.0",
    "next": "13.0.4",
    "wagmi": "^0.8.5"

**Comment by chaitanyapotti** [comment]
pls mark this package as client side only..
