### ISSUE TITLE
Changes to chain through the Torus Provider do not reflect on Wagmi

### ISSUE THREAD

**Issue by brunocangs** [Web3Auth/web3auth-wagmi-connector#40]
I currently have this connector on version `^4.2.2` set up on my repository, using code I pulled directly from the `web3-auth-examples` repo, however I'm not able to receive/detect chain changes from wagmi.

Steps to reproduce:
- Connect to your wallet using the OpenLogin with Torus embed plugin. This step connects to the correct network, even Hardhat
- Open the wallet popup and change the network

This will not trigger a change on the network value from `wagmi`'s `useNetwork`, `useProvider` or `useSigner` and it can cause serious user experience issues when trying to submit transacitons

**Comment by chaitanyapotti** [comment]
This is fixed in 3.0.0
