### ISSUE TITLE
Production build runtime error in openloginAdapater.ts (TypeError: s is not a constructor for EthereumPrivateKeyProvider), but dev build works

### ISSUE THREAD

**Issue by ryanberckmans** [Web3Auth/web3auth-wagmi-connector#44]
My dev build is working great with `@web3auth/base`, `@web3auth/core`, `@web3auth/web3auth-wagmi-connector`, and `@web3auth/openlogin-adapter`.

However, the exact same code fails with a runtime error in a locally run production build (ie. `yarn build && serve -s build`). The production build succeeds but there's a runtime error that prevents web3auth from working.

For context, I'd like to migrate my app to Vite, but am currently using create-react-app.

Btw, afaict, `@web3auth/openlogin-adapter` seems to be closed source, so I've filed the issue here.

As can be seen in the following screenshot, it seems that openloginAdapter.ts's use of `EthereumPrivateKeyProvider` isn't correctly surviving the production build compilation/minification because the reported error is `TypeError: s is not a constructor` and sourcemaps indicate the error's location is in the expression `new EthereumPrivateKeyProvider(...)`.

I can't use web3auth in production until this is fixed, or perhaps it might fix itself when I migrate from create-react-app to Vite.

![image](https://user-images.githubusercontent.com/299324/218769477-b7d515c8-99ac-45f4-bf80-d3ff8cbe0dd1.png)

**Comment by Nilbristi** [comment]
I think you need a typeScript version 4.8.4.

Or use this example code
https://github.com/Web3Auth/examples/tree/main/wagmi-connector

**Comment by chaitanyapotti** [comment]
Pls test the example with 3.0.0 and report if the issue persists

**Comment by ryanberckmans** [comment]
@chaitanyapotti 3.0.0 appears to have fixed the original issue and uncovered a new issue:
```
TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at 12513 (uint.ts:10:22)
    at n (bootstrap:19:32)
    at 49043 (index.ts:12:1)
    at n (bootstrap:19:32)
    at 20146 (ssz.ts:1:1)
    at n (bootstrap:19:32)
    at 15775 (index.ts:39:1)
    at n (bootstrap:19:32)
    at 29052 (index.js:1228:9)
 ```

I would like to use web3auth in production soon. Hopefully this issue may fix itself when I migrate from create-react-app to Vite. It'd be great to get some additional support here, thanks.

**Comment by yashovardhan** [comment]
@ryanberckmans can you open up a new https://community.web3auth.io thread around this issue you're facing now?

Also please tell us the steps to reproduce it.

**Comment by yashovardhan** [comment]
@ryanberckmans can you check if this was fixed in `3.0.1`?

**Comment by ryanberckmans** [comment]
@yashovardhan It's not fixed in `3.0.1`. Going to go ahead and close this.

**Comment by yashovardhan** [comment]
I can reproduce this issue currently. Reopening it.

**Comment by ryanberckmans** [comment]
@yashovardhan great news, I figured this one out and fixed it:

The problem is @toruslabs/base-controllers eventually depends on @chainsafe/ssz, and the ssz library statically declares values like `BigInt(2)` that webpack rewrites to be just the number `2` due to BigInt incompatibility in older browsers, and then this rewrite is used with the exponentiation operator `**` but that's unsupported for numbers (instead of BigInts), so it throws an error on import.

The surprising fix is to tell create-react-app to ignore older browsers, and then webpack will no longer remove `BigInt` literals.

Here is the fix:

Set this in `package.json` (or update existing `"browserslist"`):

```json
"browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

Here's a link describing the issue that also affected starknet.js: https://github.com/0xs34n/starknet.js/issues/37#issuecomment-955797303

For web3auth to fix this issue, I would recommend 
1. advising customers to use vite instead of create-react-app/webpack
2. but, lots of customers still use create-react-app, and lots of eth app templates use it, too. So I would (i) try to get this fix merged into every popular template, and (ii) offer your own create-react-app template that includes this fix

**Comment by ryanberckmans** [comment]
didn't mean to close it

**Comment by chaitanyapotti** [comment]
Using create react app, you can still set the browserslist to

```json
{
  "browserslist": {
    "production": ["supports bigint", "not dead"],
    "development": ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]
  }
}
```
