### ISSUE TITLE
Move this to `peerDeependencies`

### ISSUE THREAD

**Issue by dalechyn** [Web3Auth/web3auth-wagmi-connector#49]
Your guide requires in fact to use the `wagmi` package but that won't be the same package that you use, thus the strict typing is not met.

https://github.com/Web3Auth/web3auth-wagmi-connector/blob/b5ce51dc83d3799db77762122a9e049c6073bfcc/package.json#LL22C3-L22C3

**Comment by chaitanyapotti** [comment]
Fixed in 3.0.0
