### ISSUE TITLE
Property 'socialLoginConfig' is missing in type Options

### ISSUE THREAD

**Issue by fjlogrono** [Web3Auth/web3auth-wagmi-connector#6]
First of all, thank you for your work. 

I have tried to follow this [tutorial](https://docs.moralis.io/docs/sign-in-with-web3authio), but it is giving me errors in Angular when installing dependencies. I have tried with react, and I get the following error.

![imagen](https://user-images.githubusercontent.com/12831769/194108577-8c6979c7-d8b2-448b-8078-771f67eca95e.png)

Thanks

**Comment by harshrpg** [comment]
The only required parameter for socialLoginConfig is the mfa level so you can do this:

![image](https://user-images.githubusercontent.com/22921415/194522450-5cca7ed6-c76e-40e9-9444-64e94d8c2204.png)

**Comment by chaitanyapotti** [comment]
No longer relevant
