### ISSUE TITLE
Support next version of Wagmi with `viem`

### ISSUE THREAD

**Issue by Julien-R44** [Web3Auth/web3auth-wagmi-connector#65]
Wagmi is preparing version 1.0, [an RC is about to be released](https://github.com/wagmi-dev/wagmi/pull/2235). I think you know about it but they are notably totally removing the dependency on Ethers and now use Viem instead. 

So the web3auth connector for Wagmi will have to be updated. I'm already starting to work with the next version of wagmi, so this is a blocking step I'm encountering: the web3auth connector needs to be made compatible. 

There is a [reference PR here in which they migrate their built-in connectors to viem](https://github.com/wagmi-dev/references/pull/215).

Do you have any plans to do this work, maybe an ETA? 
Or should I look into it myself because you don't plan to do it before the official release of the next version of wagmi or any other reasons? 

Thanks !

**Comment by keon** [comment]
Would love to know the ETA as well. Thanks!

**Comment by sinolopes** [comment]
Many team are waiting for web3auth update to wagmi v1 and viem !

**Comment by Nilbristi** [comment]
Hello @yashovardhan and @chaitanyapotti 

The latest **@web3auth/web3auth-wagmi-connector(3.0.2)** is not working with latest **wagmi/core(1.1.1)**

**Can you give us a tentative time when you people are going to release the latest @web3auth/web3auth-wagmi-connector which will work with latest @wagmi/core?**

**Comment by yashovardhan** [comment]
This will be fixed in #78
