### ISSUE TITLE
Invalid params

### ISSUE THREAD

**Issue by marcus-sa** [Web3Auth/web3auth-wagmi-connector#66]
The guide at https://web3auth.io/docs/sdk/web/wagmi-connector doesn't work.

<img width="1203" alt="Screenshot 2023-05-14 at 23 22 31" src="https://github.com/Web3Auth/web3auth-wagmi-connector/assets/8391194/baf8fa08-037a-45ac-87f2-cb8e42ffc677">

**Comment by yashovardhan** [comment]
You can follow the examples mentioned here. There might be some bug in your code which we need to find out. Please ask us the question on https://community.web3auth.io for a prompt response.
