### ISSUE TITLE
Does/will this connector support fetchSigner and signTypedData?

### ISSUE THREAD

**Issue by RonanKMcGovern** [Web3Auth/web3auth-wagmi-connector#69]
I'm using RainbowKit and Wagmi and want to add web3auth as a wallet within RainbowKit.

My webapp uses fetchSigner and signTypedData and I'm wondering if those will work if using this connector. Thanks.

https://0.8.x.wagmi.sh/core/actions/fetchSigner

https://0.8.x.wagmi.sh/core/actions/signTypedData

**Comment by yashovardhan** [comment]
yes, all actions from wagmi are supported in this connector. For further questions, please ask us on https://community.web3auth.io
