### ISSUE TITLE
External Wallet Options is not available when using this connector

### ISSUE THREAD

**Issue by harshrpg** [Web3Auth/web3auth-wagmi-connector#7]
Hi When using this connector only social logins are available however there are some use cases where External Wallet Connections will be needed, however this is not possible to achieve with the wagmi connector for web3auth

**Comment by jjjjjjjjjjjjjjjjacob** [comment]
Yeah I'm having trouble parsing the documentation. It looks like we need to implement the `@web3auth/torus-wallet-connector-plugin` but it can only be instantiated asynchronously, which isn't how `wagmi`'s client instantiation works.

Also there's no way to configure the external wallets to show as visible once it is "working".

**Comment by chaitanyapotti** [comment]
This is fixed now
