### ISSUE TITLE
chain id response

### ISSUE THREAD

**Issue by retwn** [Web3Auth/web3auth-wagmi-connector#9]
please update main branch with fixed chainId response

**Comment by jpshankle** [comment]
agree, please merge the pr, it is needed for rainbow kit with siwe to work properly.

**Comment by pgbrandao** [comment]
🙋‍♂️

Also encountered the same problem and am looking forward to the PR being merged.

**Comment by yashovardhan** [comment]
We have merged the PR, will be releasing the new version very soon
